### ISSUE TITLE
crash on exit after I switch between VLC and Gstreamer backends 

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#128]
Hi

I'm using strawberry_0.5.3-55-g7a0f668_amd64 on Neon dev unstable distribution.
Open Strawberry settings, select "Backend" section,
switch the backend from VLC to Gstreamer,, click "Ok" button
and close Strawberry. KDE Plasma desktop environment shows
a crash notification.

```
Application: strawberry (strawberry), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f92564d5080 (LWP 4272))]

Thread 4 (Thread 0x7f91777fe700 (LWP 4305)):
#0  0x00007f9255ca3384 in __libc_read (fd=5, buf=0x7f91777f59a0, nbytes=32767) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007f9249a200ae in ?? () from /usr/lib/x86_64-linux-gnu/libusbmuxd.so.4
#2  0x00007f9249a20d41 in ?? () from /usr/lib/x86_64-linux-gnu/libusbmuxd.so.4
#3  0x00007f9255c996db in start_thread (arg=0x7f91777fe700) at pthread_create.c:463
#4  0x00007f924f21588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f9177fff700 (LWP 4304)):
#0  0x00007f924f208bf9 in __GI___poll (fds=0x7f917c025c70, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f925094c539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f925094c8d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9253cf5026 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f9250974105 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9255c996db in start_thread (arg=0x7f9177fff700) at pthread_create.c:463
#6  0x00007f924f21588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f918cff9700 (LWP 4303)):
#0  0x00007f924f208bf9 in __GI___poll (fds=0x7f917c013a80, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f925094c539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f925094c64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f925094c691 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f9250974105 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9255c996db in start_thread (arg=0x7f918cff9700) at pthread_create.c:463
#6  0x00007f924f21588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f92564d5080 (LWP 4272)):
[KCrash Handler]
#7  0x0000559d98fa3c24 in TagLib::RefCounter::deref() ()
#8  0x0000559d98f97770 in TagLib::String::~String() ()
#9  0x00007f924f137041 in __run_exit_handlers (status=0, listp=0x7f924f4df718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#10 0x00007f924f13713a in __GI_exit (status=<optimized out>) at exit.c:139
#11 0x00007f924f115b9e in __libc_start_main (main=0x559d98b62bfa <main>, argc=1, argv=0x7ffcb5acb978, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcb5acb968) at ../csu/libc-start.c:344
#12 0x0000559d98b62b1a in _start ()

``'

**Comment by jonaski** [comment]
Not sure if this crash is caused by a library or strawberry itself.
I got the nvidia workaround on my main linux machine, so I'll need to test this on another machine when I get the chance.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/3c6c9741ffafdc7ae02abe87f656a4f760fb9600

**Comment by jonaski** [comment]
Looks like the crash is still there when using the bultin taglib

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/1c926cca45ef9268ba031860b3c34db528c23bae
