### ISSUE TITLE
crash when playback selected track

### ISSUE THREAD

**Issue by martinkg** [jonaski/strawberry#18]
`martin@fc29 ~]$ gdb strawberry
GNU gdb (GDB) Fedora 8.2-2.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from strawberry...Reading symbols from /usr/lib/debug/usr/bin/strawberry-0.3.3-1.fc29.x86_64.debug...done.
done.
(gdb) r
Starting program: /usr/bin/strawberry 
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffe5165700 (LWP 22926)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffdfbb1700 (LWP 22927)]
[New Thread 0x7fffdf3b0700 (LWP 22928)]
[New Thread 0x7fffdebaf700 (LWP 22929)]
[New Thread 0x7fffde3ae700 (LWP 22930)]
[New Thread 0x7fffdd98d700 (LWP 22931)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffdd0ca700 (LWP 22933)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffb7fff700 (LWP 22934)]
[New Thread 0x7fffb77fe700 (LWP 22935)]
[New Thread 0x7fffb6ffd700 (LWP 22936)]
[New Thread 0x7fffb67fc700 (LWP 22937)]
[Detaching after fork from child process 22938]
[Detaching after fork from child process 22939]
[New Thread 0x7fffb5ffb700 (LWP 22945)]
[New Thread 0x7fffb57fa700 (LWP 22946)]
[New Thread 0x7fffb4ff9700 (LWP 22947)]
[New Thread 0x7fff9bfff700 (LWP 22948)]
[New Thread 0x7fff9b7fe700 (LWP 22949)]
[New Thread 0x7fff9affd700 (LWP 22950)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread 0x7fffdebaf700 (LWP 22929) exited]
[New Thread 0x7fffdebaf700 (LWP 22953)]
[New Thread 0x7fff8ca8b700 (LWP 22954)]
[New Thread 0x7fff8ca8b700 (LWP 22955)]
[Thread 0x7fff8ca8b700 (LWP 22954) exited]
[New Thread 0x7fff77fff700 (LWP 22956)]
[New Thread 0x7fff777fe700 (LWP 22957)]
[New Thread 0x7fff76ffd700 (LWP 22958)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fff767fc700 (LWP 22959)]
[New Thread 0x7fff75ffb700 (LWP 22960)]
[New Thread 0x7fff757fa700 (LWP 22961)]
[New Thread 0x7fff74ff9700 (LWP 22962)]
[New Thread 0x7fff747f8700 (LWP 22963)]
[New Thread 0x7fff73ff7700 (LWP 22964)]
[New Thread 0x7fff737f6700 (LWP 22965)]
[New Thread 0x7fff72ff5700 (LWP 22966)]
[New Thread 0x7fff727f4700 (LWP 22967)]
[New Thread 0x7fff71ff3700 (LWP 22968)]
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

Thread 1 "strawberry" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) bt
#0  0x00007ffff58d053f in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff58ba895 in __GI_abort () at abort.c:79
#2  0x00005555557d3c28 in std::__replacement_assert(char const*, int, char const*, char const*)
    (__file=__file@entry=0x555555b14b30 "/usr/include/c++/8/bits/stl_vector.h", __line=__line@entry=932, __function=__function@entry=0x555555d9e960 <_ZZNSt6vectorIfSaIfEEixEmE19__PRETTY_FUNCTION__> "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = f"..., __condition=__condition@entry=0x555555b14b00 "__builtin_expect(__n < this->size(), true)")
    at /usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2391
#3  0x0000555555a3a33f in std::vector<float, std::allocator<float> >::operator[](unsigned long) (__n=<optimized out>, this=0x5555560a2aa8)
    at /usr/src/debug/strawberry-0.3.3-1.fc29.x86_64/src/analyzer/analyzerbase.cpp:106
#4  0x0000555555a3a33f in Analyzer::Base::paintEvent(QPaintEvent*) (this=0x5555560a2a60, e=0x7fffffffafb0)
    at /usr/src/debug/strawberry-0.3.3-1.fc29.x86_64/src/analyzer/analyzerbase.cpp:100
#5  0x00007ffff6a69c58 in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#6  0x00007ffff6a2ab05 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#7  0x00007ffff6a32220 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#8  0x00007ffff6134456 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#9  0x00007ffff6a6277e in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /lib64/libQt5Widgets.so.5
#10 0x00007ffff6a63037 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#11 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#12 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#13 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#14 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#15 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#16 0x00007ffff6a63b20 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#17 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#18 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#19 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#20 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#21 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#22 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#23 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#24 0x00007ffff6a63c31 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#25 0x00007ffff6a63b20 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#26 0x00007ffff6a63b20 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#27 0x00007ffff6a62cbc in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /lib64/libQt5Widgets.so.5
#28 0x00007ffff6a3a11c in QWidgetBackingStore::doSync() () at /lib64/libQt5Widgets.so.5
#29 0x00007ffff6a3a2d1 in QWidgetBackingStore::sync() () at /lib64/libQt5Widgets.so.5
#30 0x00007ffff6a51ac5 in QWidgetPrivate::syncBackingStore() () at /lib64/libQt5Widgets.so.5
#31 0x00007ffff6a69d88 in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#32 0x00007ffff6b733f8 in QMainWindow::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#33 0x00007ffff6a2ab05 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#34 0x00007ffff6a32220 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#35 0x00007ffff6134456 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#36 0x00007ffff613762b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#37 0x00007ffff6184d27 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#38 0x00007ffff78af26d in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#39 0x00007ffff78af638 in  () at /lib64/libglib-2.0.so.0
#40 0x00007ffff78af6d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#41 0x00007ffff6184ab3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#42 0x00007fffe5381d95 in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5XcbQpa.so.5
#43 0x00007ffff613339b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#44 0x00007ffff613b466 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#45 0x0000555555764fd4 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/strawberry-0.3.3-1.fc29.x86_64/src/core/main.cpp:230`

**Comment by jonaski** [comment]
This seem to be the same as #17. Crash in the analyzer.
Right click on the analyzer (the area between the playlist and the progress bar) and select No analyzer. It should be a temporary workaround.
The crash should be fixed in commit 6d888eb.
You can use the tarball from http://builds.strawbs.net/source/ (0.3.3.15) until a next release.
